/*
 * Made for Capstone Project for MFC Systems Fall 2015-Spring 2016
 * Program Version 1
 * Generated By: Visual Studios 2013
 * Modified By: Ashley Krueger
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Capstone_v1
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Start_Page());
        }
    }
}
